###############################################################################
############################ Skydive ##########################################
###############################################################################

##################
## Image variables
arch:
  amd64: "2 - No preference"
  ppc64le: "2 - No preference"
  s390x: "2 - No preference"

image:
  repository: skydive/skydive
  tag: "0.24.0"
  secretName: ""
  imagePullPolicy: IfNotPresent

##################
## Resources
resources:
  limits:
    cpu: 2000m
    memory: 8192Mi
  requests:
    cpu: 100m
    memory: 512Mi

##################
## Service variables
service:
  name: skydive
  port: 8082
  type: NodePort

etcd:
  port: 12379

analyzer:
  topology:
    fabric: "TOR1->*[Type=host]/eth0"

agent:
  topology:
    probes: "ovsdb docker runc"

## env variables
env: []

###################
## Elastic search image 
elasticsearch:
  image:
    repository: "elastic/elasticsearch"
    tag: "5.5.1"

##################
## Data / Storage
##
## - Persistence disables by default
persistence:
  enabled: false
  useDynamicProvisioning: false

dataVolume:
  name: "datavolume"
  existingClaimName: ""
  storageClassName: ""
  size: 10Gi

storage:
  flows:
    indicesToKeep: 10
    indexEntriesLimit: 10000
  topology:
    indicesToKeep: 10
    indexEntriesLimit: 10000
  elasticsearch:
    port: 9200
    host: 127.0.0.1
