SRCS := \
	classify.go \
	compress.go \
	encode.go \
	filter.go \
	pipeline.go \
	main.go \
	s3_client.go \
	store_stdout.go \
	store_s3.go \
	subscriber.go \
	transform.go \

.PHONY: all
all:
	go build $(SRCS)
