// Code generated by protoc-gen-go.
// source: flow/flow.proto
// DO NOT EDIT!

/*
Package flow is a generated protocol buffer package.

It is generated from these files:
	flow/flow.proto

It has these top-level messages:
	FlowEndpointStatistics
	FlowEndpointsStatistics
	FlowStatistics
	Flow
*/
package flow

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

type FlowEndpointLayer int32

const (
	FlowEndpointLayer_LINK      FlowEndpointLayer = 0
	FlowEndpointLayer_NETWORK   FlowEndpointLayer = 1
	FlowEndpointLayer_TRANSPORT FlowEndpointLayer = 2
)

var FlowEndpointLayer_name = map[int32]string{
	0: "LINK",
	1: "NETWORK",
	2: "TRANSPORT",
}
var FlowEndpointLayer_value = map[string]int32{
	"LINK":      0,
	"NETWORK":   1,
	"TRANSPORT": 2,
}

func (x FlowEndpointLayer) String() string {
	return proto.EnumName(FlowEndpointLayer_name, int32(x))
}
func (FlowEndpointLayer) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type FlowEndpointType int32

const (
	FlowEndpointType_ETHERNET FlowEndpointType = 0
	FlowEndpointType_IPV4     FlowEndpointType = 1
	FlowEndpointType_TCPPORT  FlowEndpointType = 2
	FlowEndpointType_UDPPORT  FlowEndpointType = 3
	FlowEndpointType_SCTPPORT FlowEndpointType = 4
)

var FlowEndpointType_name = map[int32]string{
	0: "ETHERNET",
	1: "IPV4",
	2: "TCPPORT",
	3: "UDPPORT",
	4: "SCTPPORT",
}
var FlowEndpointType_value = map[string]int32{
	"ETHERNET": 0,
	"IPV4":     1,
	"TCPPORT":  2,
	"UDPPORT":  3,
	"SCTPPORT": 4,
}

func (x FlowEndpointType) String() string {
	return proto.EnumName(FlowEndpointType_name, int32(x))
}
func (FlowEndpointType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type FlowEndpointStatistics struct {
	Value   string `protobuf:"bytes,2,opt,name=Value" json:"Value,omitempty"`
	Packets uint64 `protobuf:"varint,5,opt,name=Packets" json:"Packets,omitempty"`
	Bytes   uint64 `protobuf:"varint,6,opt,name=Bytes" json:"Bytes,omitempty"`
}

func (m *FlowEndpointStatistics) Reset()                    { *m = FlowEndpointStatistics{} }
func (m *FlowEndpointStatistics) String() string            { return proto.CompactTextString(m) }
func (*FlowEndpointStatistics) ProtoMessage()               {}
func (*FlowEndpointStatistics) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type FlowEndpointsStatistics struct {
	Type FlowEndpointType        `protobuf:"varint,1,opt,name=Type,enum=flow.FlowEndpointType" json:"Type,omitempty"`
	Hash []byte                  `protobuf:"bytes,2,opt,name=Hash,proto3" json:"Hash,omitempty"`
	AB   *FlowEndpointStatistics `protobuf:"bytes,3,opt,name=AB" json:"AB,omitempty"`
	BA   *FlowEndpointStatistics `protobuf:"bytes,4,opt,name=BA" json:"BA,omitempty"`
}

func (m *FlowEndpointsStatistics) Reset()                    { *m = FlowEndpointsStatistics{} }
func (m *FlowEndpointsStatistics) String() string            { return proto.CompactTextString(m) }
func (*FlowEndpointsStatistics) ProtoMessage()               {}
func (*FlowEndpointsStatistics) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *FlowEndpointsStatistics) GetAB() *FlowEndpointStatistics {
	if m != nil {
		return m.AB
	}
	return nil
}

func (m *FlowEndpointsStatistics) GetBA() *FlowEndpointStatistics {
	if m != nil {
		return m.BA
	}
	return nil
}

type FlowStatistics struct {
	Start     int64                      `protobuf:"varint,1,opt,name=Start" json:"Start,omitempty"`
	Last      int64                      `protobuf:"varint,2,opt,name=Last" json:"Last,omitempty"`
	Endpoints []*FlowEndpointsStatistics `protobuf:"bytes,3,rep,name=Endpoints" json:"Endpoints,omitempty"`
}

func (m *FlowStatistics) Reset()                    { *m = FlowStatistics{} }
func (m *FlowStatistics) String() string            { return proto.CompactTextString(m) }
func (*FlowStatistics) ProtoMessage()               {}
func (*FlowStatistics) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *FlowStatistics) GetEndpoints() []*FlowEndpointsStatistics {
	if m != nil {
		return m.Endpoints
	}
	return nil
}

type Flow struct {
	// Flow Universally Unique IDentifier
	//
	// flow.UUID is unique in the universe, as it should be used as a key of an
	// hashtable. By design 2 different flows, their UUID are always different.
	// flow.UUID can be used as Database Index.
	UUID       string `protobuf:"bytes,1,opt,name=UUID" json:"UUID,omitempty"`
	LayersPath string `protobuf:"bytes,2,opt,name=LayersPath" json:"LayersPath,omitempty"`
	// Data Flow info
	Statistics *FlowStatistics `protobuf:"bytes,3,opt,name=Statistics" json:"Statistics,omitempty"`
	// Flow Tracking IDentifier, from 1st packet bytes
	//
	// flow.TrackingID could be used to identify an unique flow whatever it has
	// been captured on the infrastructure. flow.TrackingID is calculated from
	// the bytes of the first packet of his session.
	// flow.TrackingID can be used as a Tag.
	TrackingID string `protobuf:"bytes,5,opt,name=TrackingID" json:"TrackingID,omitempty"`
	// Topology info
	ProbeNodeUUID string `protobuf:"bytes,11,opt,name=ProbeNodeUUID" json:"ProbeNodeUUID,omitempty"`
	IfSrcNodeUUID string `protobuf:"bytes,14,opt,name=IfSrcNodeUUID" json:"IfSrcNodeUUID,omitempty"`
	IfDstNodeUUID string `protobuf:"bytes,19,opt,name=IfDstNodeUUID" json:"IfDstNodeUUID,omitempty"`
}

func (m *Flow) Reset()                    { *m = Flow{} }
func (m *Flow) String() string            { return proto.CompactTextString(m) }
func (*Flow) ProtoMessage()               {}
func (*Flow) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Flow) GetStatistics() *FlowStatistics {
	if m != nil {
		return m.Statistics
	}
	return nil
}

func init() {
	proto.RegisterType((*FlowEndpointStatistics)(nil), "flow.FlowEndpointStatistics")
	proto.RegisterType((*FlowEndpointsStatistics)(nil), "flow.FlowEndpointsStatistics")
	proto.RegisterType((*FlowStatistics)(nil), "flow.FlowStatistics")
	proto.RegisterType((*Flow)(nil), "flow.Flow")
	proto.RegisterEnum("flow.FlowEndpointLayer", FlowEndpointLayer_name, FlowEndpointLayer_value)
	proto.RegisterEnum("flow.FlowEndpointType", FlowEndpointType_name, FlowEndpointType_value)
}

var fileDescriptor0 = []byte{
	// 461 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x8c, 0x53, 0x41, 0x6f, 0xd3, 0x30,
	0x14, 0xa6, 0x89, 0xb3, 0x2e, 0xaf, 0x6b, 0x29, 0x66, 0x1a, 0x39, 0x00, 0x42, 0x15, 0x07, 0x54,
	0xa1, 0x21, 0x8d, 0x5d, 0x10, 0xa7, 0x76, 0x2d, 0x5a, 0xb5, 0xa9, 0x8b, 0x5c, 0x77, 0xdc, 0x90,
	0x9c, 0xce, 0xa3, 0x11, 0x51, 0x13, 0xc5, 0x1e, 0x53, 0xaf, 0xfc, 0x27, 0xfe, 0x1f, 0xcf, 0xce,
	0x96, 0x18, 0x7a, 0xe1, 0x92, 0xbe, 0xef, 0xcb, 0xf7, 0xde, 0xf7, 0xf9, 0xb9, 0x81, 0xa7, 0xb7,
	0x59, 0x7e, 0xff, 0xc1, 0x3c, 0x8e, 0x8b, 0x32, 0xd7, 0x39, 0x25, 0xa6, 0x1e, 0x7c, 0x83, 0xa3,
	0x2f, 0xf8, 0x3b, 0xdd, 0xdc, 0x14, 0x79, 0xba, 0xd1, 0x0b, 0x2d, 0x74, 0xaa, 0x74, 0xba, 0x52,
	0xf4, 0x10, 0x82, 0x6b, 0x91, 0xdd, 0xc9, 0xc8, 0x7b, 0xd3, 0x7a, 0x17, 0xb2, 0xe0, 0xa7, 0x01,
	0x34, 0x82, 0x76, 0x2c, 0x56, 0x3f, 0xa4, 0x56, 0x51, 0x80, 0x3c, 0x61, 0xed, 0xa2, 0x82, 0x46,
	0x3f, 0xde, 0x6a, 0xa9, 0xa2, 0x3d, 0xcb, 0x07, 0x89, 0x01, 0x83, 0xdf, 0x2d, 0x78, 0xe1, 0x1a,
	0x28, 0xc7, 0x61, 0x08, 0x84, 0x6f, 0x0b, 0x19, 0xb5, 0xb0, 0xa1, 0x77, 0x72, 0x74, 0x6c, 0xc3,
	0xb9, 0x62, 0xf3, 0x96, 0x11, 0x8d, 0x4f, 0x4a, 0x81, 0x9c, 0x0b, 0xb5, 0xb6, 0x61, 0x0e, 0x18,
	0x59, 0x63, 0x4d, 0xdf, 0x83, 0x37, 0x1a, 0x47, 0x3e, 0x32, 0x9d, 0x93, 0x97, 0xbb, 0xdd, 0x8d,
	0x13, 0xf3, 0xc4, 0xd8, 0xa8, 0xc7, 0xa3, 0x88, 0xfc, 0x8f, 0x3a, 0x19, 0x0d, 0xee, 0xa1, 0x67,
	0xde, 0xfe, 0xbd, 0x0f, 0x44, 0xa5, 0xb6, 0x71, 0x7d, 0x16, 0x28, 0x03, 0x4c, 0xae, 0x4b, 0xa1,
	0xb4, 0xcd, 0xe5, 0x33, 0x92, 0x61, 0x4d, 0x3f, 0x43, 0x58, 0x1f, 0x17, 0xe3, 0xf9, 0x68, 0xf8,
	0x6a, 0xd7, 0xd0, 0xd9, 0x04, 0x0b, 0xe5, 0x23, 0x39, 0xf8, 0xe5, 0x01, 0x31, 0x32, 0x33, 0x79,
	0xb9, 0x9c, 0x4d, 0xac, 0x5d, 0xc8, 0xc8, 0x1d, 0xd6, 0xf4, 0x35, 0xc0, 0xa5, 0xd8, 0xca, 0x52,
	0xc5, 0x42, 0xaf, 0x1f, 0x2e, 0x06, 0xb2, 0x9a, 0xa1, 0xa7, 0x00, 0xcd, 0xd4, 0x87, 0xcd, 0x1c,
	0x36, 0xd6, 0x8e, 0x23, 0xa8, 0xe6, 0x64, 0x38, 0x95, 0x97, 0x78, 0x8b, 0xe9, 0xe6, 0x3b, 0xfa,
	0x05, 0xd5, 0x54, 0x5d, 0x33, 0xf4, 0x2d, 0x74, 0xe3, 0x32, 0x4f, 0xe4, 0x3c, 0xbf, 0x91, 0x36,
	0x52, 0xc7, 0x4a, 0xba, 0x85, 0x4b, 0x1a, 0xd5, 0xec, 0x76, 0x51, 0xae, 0x6a, 0x55, 0xaf, 0x52,
	0xa5, 0x2e, 0x59, 0xa9, 0x26, 0x4a, 0xd7, 0xaa, 0xe7, 0x8f, 0x2a, 0x87, 0x1c, 0x7e, 0x82, 0x67,
	0xee, 0xaa, 0xec, 0x99, 0xe9, 0x3e, 0xae, 0x7a, 0x36, 0xbf, 0xe8, 0x3f, 0xa1, 0x1d, 0x68, 0xcf,
	0xa7, 0xfc, 0xeb, 0x15, 0xbb, 0xe8, 0xb7, 0x68, 0x17, 0x42, 0xce, 0x46, 0xf3, 0x45, 0x7c, 0xc5,
	0x78, 0xdf, 0x1b, 0x32, 0xe8, 0xff, 0xfb, 0x17, 0xa2, 0x07, 0xb0, 0x3f, 0xe5, 0xe7, 0x53, 0x86,
	0x4d, 0xd8, 0x8d, 0x73, 0x66, 0xf1, 0xf5, 0x29, 0xb6, 0xe2, 0x1c, 0x7e, 0x16, 0x57, 0x8d, 0x06,
	0x2c, 0x27, 0x15, 0xf0, 0x4d, 0xc7, 0xe2, 0x8c, 0x57, 0x88, 0x24, 0x7b, 0xf6, 0x8b, 0xf9, 0xf8,
	0x27, 0x00, 0x00, 0xff, 0xff, 0x31, 0xd1, 0xf5, 0x76, 0x44, 0x03, 0x00, 0x00,
}
