SRCS := \
	classify.go \
	compress.go \
	encode.go \
	filter.go \
	pipeline.go \
	main.go \
	mangle.go \
	store_buffered.go \
	store_direct.go \
	subscriber.go \
	transform.go \
	write_s3.go \
	write_stdout.go \

.PHONY: all
all:
	go build $(SRCS)
