//go:generate go run github.com/skydive-project/skydive/graffiti/gendecoder -package github.com/skydive-project/skydive/topology/probes/ovn/ovnmodel
//go:generate go run github.com/mailru/easyjson/easyjson $GOFILE

// Code generated by ovnmetagen
// DO NOT EDIT.

package ovnmodel

import (
	"encoding/json"
	"fmt"

	"github.com/skydive-project/skydive/graffiti/getter"
	"github.com/skydive-project/skydive/graffiti/graph"
)

// Connection defines the type used by both libovsdb and skydive for table Connection
// easyjson:json
// gendecoder
type Connection struct {
	UUID            string            `ovsdb:"_uuid" json:",omitempty" `
	ExternalIDs     map[string]string `ovsdb:"external_ids" json:",omitempty" `
	InactivityProbe []int             `ovsdb:"inactivity_probe" json:",omitempty" `
	IsConnected     bool              `ovsdb:"is_connected" json:",omitempty" `
	MaxBackoff      []int             `ovsdb:"max_backoff" json:",omitempty" `
	OtherConfig     map[string]string `ovsdb:"other_config" json:",omitempty" `
	Status          map[string]string `ovsdb:"status" json:",omitempty" `
	Target          string            `ovsdb:"target" json:",omitempty" `

	ExternalIDsMeta graph.Metadata `json:",omitempty" field:"Metadata"`
	OtherConfigMeta graph.Metadata `json:",omitempty" field:"Metadata"`
	StatusMeta      graph.Metadata `json:",omitempty" field:"Metadata"`
}

func (t *Connection) Metadata() graph.Metadata {
	// Generate Metadata from maps
	t.ExternalIDsMeta = graph.NormalizeValue(t.ExternalIDs).(map[string]interface{})
	t.OtherConfigMeta = graph.NormalizeValue(t.OtherConfig).(map[string]interface{})
	t.StatusMeta = graph.NormalizeValue(t.Status).(map[string]interface{})

	return graph.Metadata{
		"Type":    "Connection",
		"Manager": "ovn",
		"UUID":    t.GetUUID(),
		"Name":    t.GetName(),
		"OVN":     t,
	}
}

func (t *Connection) GetUUID() string {
	return t.UUID
}

func (t *Connection) GetName() string {
	if name := t.UUID; name != "" {
		return name
	}
	return t.GetUUID()
}

// ConnectionDecoder implements a json message raw decoder
func ConnectionDecoder(raw json.RawMessage) (getter.Getter, error) {
	var t Connection
	if err := json.Unmarshal(raw, &t); err != nil {
		return nil, fmt.Errorf("unable to unmarshal Connection metadata %s: %s", string(raw), err)
	}
	return &t, nil
}
