//go:generate go run github.com/skydive-project/skydive/graffiti/gendecoder -package github.com/skydive-project/skydive/topology/probes/ovn/ovnmodel
//go:generate go run github.com/mailru/easyjson/easyjson $GOFILE

// Code generated by ovnmetagen
// DO NOT EDIT.

package ovnmodel

import (
	"encoding/json"
	"fmt"

	"github.com/skydive-project/skydive/graffiti/getter"
	"github.com/skydive-project/skydive/graffiti/graph"
)

// LoadBalancerHealthCheck defines the type used by both libovsdb and skydive for table Load_Balancer_Health_Check
// easyjson:json
// gendecoder
type LoadBalancerHealthCheck struct {
	UUID        string            `ovsdb:"_uuid" json:",omitempty" `
	ExternalIDs map[string]string `ovsdb:"external_ids" json:",omitempty" `
	Options     map[string]string `ovsdb:"options" json:",omitempty" `
	Vip         string            `ovsdb:"vip" json:",omitempty" `

	ExternalIDsMeta graph.Metadata `json:",omitempty" field:"Metadata"`
	OptionsMeta     graph.Metadata `json:",omitempty" field:"Metadata"`
}

func (t *LoadBalancerHealthCheck) Metadata() graph.Metadata {
	// Generate Metadata from maps
	t.ExternalIDsMeta = graph.NormalizeValue(t.ExternalIDs).(map[string]interface{})
	t.OptionsMeta = graph.NormalizeValue(t.Options).(map[string]interface{})

	return graph.Metadata{
		"Type":    "LoadBalancerHealthCheck",
		"Manager": "ovn",
		"UUID":    t.GetUUID(),
		"Name":    t.GetName(),
		"OVN":     t,
	}
}

func (t *LoadBalancerHealthCheck) GetUUID() string {
	return t.UUID
}

func (t *LoadBalancerHealthCheck) GetName() string {
	if name := t.UUID; name != "" {
		return name
	}
	return t.GetUUID()
}

// LoadBalancerHealthCheckDecoder implements a json message raw decoder
func LoadBalancerHealthCheckDecoder(raw json.RawMessage) (getter.Getter, error) {
	var t LoadBalancerHealthCheck
	if err := json.Unmarshal(raw, &t); err != nil {
		return nil, fmt.Errorf("unable to unmarshal LoadBalancerHealthCheck metadata %s: %s", string(raw), err)
	}
	return &t, nil
}
