//go:generate go run github.com/skydive-project/skydive/graffiti/gendecoder -package github.com/skydive-project/skydive/topology/probes/ovn/ovnmodel
//go:generate go run github.com/mailru/easyjson/easyjson $GOFILE

// Code generated by ovnmetagen
// DO NOT EDIT.

package ovnmodel

import (
	"encoding/json"
	"fmt"

	"github.com/skydive-project/skydive/graffiti/getter"
	"github.com/skydive-project/skydive/graffiti/graph"
)

// LogicalRouter defines the type used by both libovsdb and skydive for table Logical_Router
// easyjson:json
// gendecoder
type LogicalRouter struct {
	UUID         string            `ovsdb:"_uuid" json:",omitempty" `
	Enabled      []bool            `ovsdb:"enabled" json:",omitempty" `
	ExternalIDs  map[string]string `ovsdb:"external_ids" json:",omitempty" `
	LoadBalancer []string          `ovsdb:"load_balancer" json:",omitempty" `
	Name         string            `ovsdb:"name" json:",omitempty" `
	Nat          []string          `ovsdb:"nat" json:",omitempty" `
	Options      map[string]string `ovsdb:"options" json:",omitempty" `
	Policies     []string          `ovsdb:"policies" json:",omitempty" `
	Ports        []string          `ovsdb:"ports" json:",omitempty" `
	StaticRoutes []string          `ovsdb:"static_routes" json:",omitempty" `

	ExternalIDsMeta graph.Metadata `json:",omitempty" field:"Metadata"`
	OptionsMeta     graph.Metadata `json:",omitempty" field:"Metadata"`
}

func (t *LogicalRouter) Metadata() graph.Metadata {
	// Generate Metadata from maps
	t.ExternalIDsMeta = graph.NormalizeValue(t.ExternalIDs).(map[string]interface{})
	t.OptionsMeta = graph.NormalizeValue(t.Options).(map[string]interface{})

	return graph.Metadata{
		"Type":    "LogicalRouter",
		"Manager": "ovn",
		"UUID":    t.GetUUID(),
		"Name":    t.GetName(),
		"OVN":     t,
	}
}

func (t *LogicalRouter) GetUUID() string {
	return t.UUID
}

func (t *LogicalRouter) GetName() string {
	if name := t.Name; name != "" {
		return name
	}
	return t.GetUUID()
}

// LogicalRouterDecoder implements a json message raw decoder
func LogicalRouterDecoder(raw json.RawMessage) (getter.Getter, error) {
	var t LogicalRouter
	if err := json.Unmarshal(raw, &t); err != nil {
		return nil, fmt.Errorf("unable to unmarshal LogicalRouter metadata %s: %s", string(raw), err)
	}
	return &t, nil
}
