//go:generate go run github.com/skydive-project/skydive/graffiti/gendecoder -package github.com/skydive-project/skydive/topology/probes/ovn/ovnmodel
//go:generate go run github.com/mailru/easyjson/easyjson $GOFILE

// Code generated by ovnmetagen
// DO NOT EDIT.

package ovnmodel

import (
	"encoding/json"
	"fmt"

	"github.com/skydive-project/skydive/graffiti/getter"
	"github.com/skydive-project/skydive/graffiti/graph"
)

// LogicalSwitch defines the type used by both libovsdb and skydive for table Logical_Switch
// easyjson:json
// gendecoder
type LogicalSwitch struct {
	UUID             string            `ovsdb:"_uuid" json:",omitempty" `
	ACLs             []string          `ovsdb:"acls" json:",omitempty" `
	DNSRecords       []string          `ovsdb:"dns_records" json:",omitempty" `
	ExternalIDs      map[string]string `ovsdb:"external_ids" json:",omitempty" `
	ForwardingGroups []string          `ovsdb:"forwarding_groups" json:",omitempty" `
	LoadBalancer     []string          `ovsdb:"load_balancer" json:",omitempty" `
	Name             string            `ovsdb:"name" json:",omitempty" `
	OtherConfig      map[string]string `ovsdb:"other_config" json:",omitempty" `
	Ports            []string          `ovsdb:"ports" json:",omitempty" `
	QOSRules         []string          `ovsdb:"qos_rules" json:",omitempty" `

	ExternalIDsMeta graph.Metadata `json:",omitempty" field:"Metadata"`
	OtherConfigMeta graph.Metadata `json:",omitempty" field:"Metadata"`
}

func (t *LogicalSwitch) Metadata() graph.Metadata {
	// Generate Metadata from maps
	t.ExternalIDsMeta = graph.NormalizeValue(t.ExternalIDs).(map[string]interface{})
	t.OtherConfigMeta = graph.NormalizeValue(t.OtherConfig).(map[string]interface{})

	return graph.Metadata{
		"Type":    "LogicalSwitch",
		"Manager": "ovn",
		"UUID":    t.GetUUID(),
		"Name":    t.GetName(),
		"OVN":     t,
	}
}

func (t *LogicalSwitch) GetUUID() string {
	return t.UUID
}

func (t *LogicalSwitch) GetName() string {
	if name := t.Name; name != "" {
		return name
	}
	return t.GetUUID()
}

// LogicalSwitchDecoder implements a json message raw decoder
func LogicalSwitchDecoder(raw json.RawMessage) (getter.Getter, error) {
	var t LogicalSwitch
	if err := json.Unmarshal(raw, &t); err != nil {
		return nil, fmt.Errorf("unable to unmarshal LogicalSwitch metadata %s: %s", string(raw), err)
	}
	return &t, nil
}
