//go:generate go run github.com/skydive-project/skydive/graffiti/gendecoder -package github.com/skydive-project/skydive/topology/probes/ovn/ovnmodel
//go:generate go run github.com/mailru/easyjson/easyjson $GOFILE

// Code generated by ovnmetagen
// DO NOT EDIT.

package ovnmodel

import (
	"encoding/json"
	"fmt"

	"github.com/skydive-project/skydive/graffiti/getter"
	"github.com/skydive-project/skydive/graffiti/graph"
)

// MeterBand defines the type used by both libovsdb and skydive for table Meter_Band
// easyjson:json
// gendecoder
type MeterBand struct {
	UUID        string            `ovsdb:"_uuid" json:",omitempty" `
	Action      string            `ovsdb:"action" json:",omitempty" `
	BurstSize   int               `ovsdb:"burst_size" json:",omitempty" `
	ExternalIDs map[string]string `ovsdb:"external_ids" json:",omitempty" `
	Rate        int               `ovsdb:"rate" json:",omitempty" `

	ExternalIDsMeta graph.Metadata `json:",omitempty" field:"Metadata"`
}

func (t *MeterBand) Metadata() graph.Metadata {
	// Generate Metadata from maps
	t.ExternalIDsMeta = graph.NormalizeValue(t.ExternalIDs).(map[string]interface{})

	return graph.Metadata{
		"Type":    "MeterBand",
		"Manager": "ovn",
		"UUID":    t.GetUUID(),
		"Name":    t.GetName(),
		"OVN":     t,
	}
}

func (t *MeterBand) GetUUID() string {
	return t.UUID
}

func (t *MeterBand) GetName() string {
	if name := t.UUID; name != "" {
		return name
	}
	return t.GetUUID()
}

// MeterBandDecoder implements a json message raw decoder
func MeterBandDecoder(raw json.RawMessage) (getter.Getter, error) {
	var t MeterBand
	if err := json.Unmarshal(raw, &t); err != nil {
		return nil, fmt.Errorf("unable to unmarshal MeterBand metadata %s: %s", string(raw), err)
	}
	return &t, nil
}
