//go:generate go run github.com/skydive-project/skydive/graffiti/gendecoder -package github.com/skydive-project/skydive/topology/probes/ovn/ovnmodel
//go:generate go run github.com/mailru/easyjson/easyjson $GOFILE

// Code generated by ovnmetagen
// DO NOT EDIT.

package ovnmodel

import (
	"encoding/json"
	"fmt"

	"github.com/skydive-project/skydive/graffiti/getter"
	"github.com/skydive-project/skydive/graffiti/graph"
)

// PortGroup defines the type used by both libovsdb and skydive for table Port_Group
// easyjson:json
// gendecoder
type PortGroup struct {
	UUID        string            `ovsdb:"_uuid" json:",omitempty" `
	ACLs        []string          `ovsdb:"acls" json:",omitempty" `
	ExternalIDs map[string]string `ovsdb:"external_ids" json:",omitempty" `
	Name        string            `ovsdb:"name" json:",omitempty" `
	Ports       []string          `ovsdb:"ports" json:",omitempty" `

	ExternalIDsMeta graph.Metadata `json:",omitempty" field:"Metadata"`
}

func (t *PortGroup) Metadata() graph.Metadata {
	// Generate Metadata from maps
	t.ExternalIDsMeta = graph.NormalizeValue(t.ExternalIDs).(map[string]interface{})

	return graph.Metadata{
		"Type":    "PortGroup",
		"Manager": "ovn",
		"UUID":    t.GetUUID(),
		"Name":    t.GetName(),
		"OVN":     t,
	}
}

func (t *PortGroup) GetUUID() string {
	return t.UUID
}

func (t *PortGroup) GetName() string {
	if name := t.Name; name != "" {
		return name
	}
	return t.GetUUID()
}

// PortGroupDecoder implements a json message raw decoder
func PortGroupDecoder(raw json.RawMessage) (getter.Getter, error) {
	var t PortGroup
	if err := json.Unmarshal(raw, &t); err != nil {
		return nil, fmt.Errorf("unable to unmarshal PortGroup metadata %s: %s", string(raw), err)
	}
	return &t, nil
}
