apiVersion: v1
kind: ServiceAccount
metadata:
  name: skydive-service-account
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
imagePullSecrets:
  - name: sa-{{ .Release.Namespace }}
{{- if ne .Values.image.secretName "" }}
  - name: {{ .Values.image.secretName }}
{{- end }}
