// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v3.12.4
// source: flow/layers/dhcpv4.proto

package layers

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// LayerDHCPv4 wrapper to generate extra layer
type DHCPv4 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Contents     []byte `protobuf:"bytes,1,opt,name=contents,proto3" json:"contents,omitempty"`
	Payload      []byte `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	HardwareLen  uint32 `protobuf:"varint,3,opt,name=hardware_len,json=hardwareLen,proto3" json:"hardware_len,omitempty"`
	HardwareOpts uint32 `protobuf:"varint,4,opt,name=hardware_opts,json=hardwareOpts,proto3" json:"hardware_opts,omitempty"`
	Xid          uint32 `protobuf:"varint,5,opt,name=xid,proto3" json:"xid,omitempty"`
	Secs         uint32 `protobuf:"varint,6,opt,name=secs,proto3" json:"secs,omitempty"`
	Flags        uint32 `protobuf:"varint,7,opt,name=flags,proto3" json:"flags,omitempty"`
	ServerName   []byte `protobuf:"bytes,8,opt,name=server_name,json=serverName,proto3" json:"server_name,omitempty"`
	File         []byte `protobuf:"bytes,9,opt,name=file,proto3" json:"file,omitempty"`
}

func (x *DHCPv4) Reset() {
	*x = DHCPv4{}
	if protoimpl.UnsafeEnabled {
		mi := &file_flow_layers_dhcpv4_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DHCPv4) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DHCPv4) ProtoMessage() {}

func (x *DHCPv4) ProtoReflect() protoreflect.Message {
	mi := &file_flow_layers_dhcpv4_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DHCPv4.ProtoReflect.Descriptor instead.
func (*DHCPv4) Descriptor() ([]byte, []int) {
	return file_flow_layers_dhcpv4_proto_rawDescGZIP(), []int{0}
}

func (x *DHCPv4) GetContents() []byte {
	if x != nil {
		return x.Contents
	}
	return nil
}

func (x *DHCPv4) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *DHCPv4) GetHardwareLen() uint32 {
	if x != nil {
		return x.HardwareLen
	}
	return 0
}

func (x *DHCPv4) GetHardwareOpts() uint32 {
	if x != nil {
		return x.HardwareOpts
	}
	return 0
}

func (x *DHCPv4) GetXid() uint32 {
	if x != nil {
		return x.Xid
	}
	return 0
}

func (x *DHCPv4) GetSecs() uint32 {
	if x != nil {
		return x.Secs
	}
	return 0
}

func (x *DHCPv4) GetFlags() uint32 {
	if x != nil {
		return x.Flags
	}
	return 0
}

func (x *DHCPv4) GetServerName() []byte {
	if x != nil {
		return x.ServerName
	}
	return nil
}

func (x *DHCPv4) GetFile() []byte {
	if x != nil {
		return x.File
	}
	return nil
}

var File_flow_layers_dhcpv4_proto protoreflect.FileDescriptor

var file_flow_layers_dhcpv4_proto_rawDesc = []byte{
	0x0a, 0x18, 0x66, 0x6c, 0x6f, 0x77, 0x2f, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x2f, 0x64, 0x68,
	0x63, 0x70, 0x76, 0x34, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x6c, 0x61, 0x79, 0x65,
	0x72, 0x73, 0x22, 0xf7, 0x01, 0x0a, 0x06, 0x44, 0x48, 0x43, 0x50, 0x76, 0x34, 0x12, 0x1a, 0x0a,
	0x08, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x08, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x61, 0x79,
	0x6c, 0x6f, 0x61, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x70, 0x61, 0x79, 0x6c,
	0x6f, 0x61, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x68, 0x61, 0x72, 0x64, 0x77, 0x61, 0x72, 0x65, 0x5f,
	0x6c, 0x65, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x68, 0x61, 0x72, 0x64, 0x77,
	0x61, 0x72, 0x65, 0x4c, 0x65, 0x6e, 0x12, 0x23, 0x0a, 0x0d, 0x68, 0x61, 0x72, 0x64, 0x77, 0x61,
	0x72, 0x65, 0x5f, 0x6f, 0x70, 0x74, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0c, 0x68,
	0x61, 0x72, 0x64, 0x77, 0x61, 0x72, 0x65, 0x4f, 0x70, 0x74, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x78,
	0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x78, 0x69, 0x64, 0x12, 0x12, 0x0a,
	0x04, 0x73, 0x65, 0x63, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x73, 0x65, 0x63,
	0x73, 0x12, 0x14, 0x0a, 0x05, 0x66, 0x6c, 0x61, 0x67, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x05, 0x66, 0x6c, 0x61, 0x67, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0a, 0x73, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x69, 0x6c, 0x65,
	0x18, 0x09, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x66, 0x69, 0x6c, 0x65, 0x42, 0x30, 0x5a, 0x2e,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x6b, 0x79, 0x64, 0x69,
	0x76, 0x65, 0x2d, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x2f, 0x73, 0x6b, 0x79, 0x64, 0x69,
	0x76, 0x65, 0x2f, 0x66, 0x6c, 0x6f, 0x77, 0x2f, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_flow_layers_dhcpv4_proto_rawDescOnce sync.Once
	file_flow_layers_dhcpv4_proto_rawDescData = file_flow_layers_dhcpv4_proto_rawDesc
)

func file_flow_layers_dhcpv4_proto_rawDescGZIP() []byte {
	file_flow_layers_dhcpv4_proto_rawDescOnce.Do(func() {
		file_flow_layers_dhcpv4_proto_rawDescData = protoimpl.X.CompressGZIP(file_flow_layers_dhcpv4_proto_rawDescData)
	})
	return file_flow_layers_dhcpv4_proto_rawDescData
}

var file_flow_layers_dhcpv4_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_flow_layers_dhcpv4_proto_goTypes = []interface{}{
	(*DHCPv4)(nil), // 0: layers.DHCPv4
}
var file_flow_layers_dhcpv4_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_flow_layers_dhcpv4_proto_init() }
func file_flow_layers_dhcpv4_proto_init() {
	if File_flow_layers_dhcpv4_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_flow_layers_dhcpv4_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DHCPv4); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_flow_layers_dhcpv4_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_flow_layers_dhcpv4_proto_goTypes,
		DependencyIndexes: file_flow_layers_dhcpv4_proto_depIdxs,
		MessageInfos:      file_flow_layers_dhcpv4_proto_msgTypes,
	}.Build()
	File_flow_layers_dhcpv4_proto = out.File
	file_flow_layers_dhcpv4_proto_rawDesc = nil
	file_flow_layers_dhcpv4_proto_goTypes = nil
	file_flow_layers_dhcpv4_proto_depIdxs = nil
}
