// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package ondemand

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
	graph "github.com/skydive-project/skydive/graffiti/graph"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonBbc2492aDecodeGithubComSkydiveProjectSkydiveGraffitiOndemand(in *jlexer.Lexer, out *RawQuery) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "NodeID":
			out.NodeID = graph.Identifier(in.String())
		case "Resource":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.Resource).UnmarshalJSON(data))
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonBbc2492aEncodeGithubComSkydiveProjectSkydiveGraffitiOndemand(out *jwriter.Writer, in RawQuery) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"NodeID\":"
		out.RawString(prefix[1:])
		out.String(string(in.NodeID))
	}
	{
		const prefix string = ",\"Resource\":"
		out.RawString(prefix)
		out.Raw((in.Resource).MarshalJSON())
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v RawQuery) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonBbc2492aEncodeGithubComSkydiveProjectSkydiveGraffitiOndemand(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v RawQuery) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonBbc2492aEncodeGithubComSkydiveProjectSkydiveGraffitiOndemand(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *RawQuery) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonBbc2492aDecodeGithubComSkydiveProjectSkydiveGraffitiOndemand(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *RawQuery) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonBbc2492aDecodeGithubComSkydiveProjectSkydiveGraffitiOndemand(l, v)
}
func easyjsonBbc2492aDecodeGithubComSkydiveProjectSkydiveGraffitiOndemand1(in *jlexer.Lexer, out *Query) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "NodeID":
			out.NodeID = graph.Identifier(in.String())
		case "Resource":
			if m, ok := out.Resource.(easyjson.Unmarshaler); ok {
				m.UnmarshalEasyJSON(in)
			} else if m, ok := out.Resource.(json.Unmarshaler); ok {
				_ = m.UnmarshalJSON(in.Raw())
			} else {
				out.Resource = in.Interface()
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonBbc2492aEncodeGithubComSkydiveProjectSkydiveGraffitiOndemand1(out *jwriter.Writer, in Query) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"NodeID\":"
		out.RawString(prefix[1:])
		out.String(string(in.NodeID))
	}
	{
		const prefix string = ",\"Resource\":"
		out.RawString(prefix)
		if m, ok := in.Resource.(easyjson.Marshaler); ok {
			m.MarshalEasyJSON(out)
		} else if m, ok := in.Resource.(json.Marshaler); ok {
			out.Raw(m.MarshalJSON())
		} else {
			out.Raw(json.Marshal(in.Resource))
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Query) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonBbc2492aEncodeGithubComSkydiveProjectSkydiveGraffitiOndemand1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Query) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonBbc2492aEncodeGithubComSkydiveProjectSkydiveGraffitiOndemand1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Query) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonBbc2492aDecodeGithubComSkydiveProjectSkydiveGraffitiOndemand1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Query) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonBbc2492aDecodeGithubComSkydiveProjectSkydiveGraffitiOndemand1(l, v)
}
