---
- name: Install elasticsearch GPG key
  rpm_key:
    state: present
    key: https://packages.elastic.co/GPG-KEY-elasticsearch

- name: Install elasticsearch YUM repository
  yum_repository:
    state: present
    name: elasticsearch
    description: Elasticsearch repository for 5.x packages
    gpgcheck: true
    gpgkey: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    baseurl: https://artifacts.elastic.co/packages/5.x/yum

- name: Install elasticsearch package
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - java
    - elasticsearch

- name: Set elasticsearch minimum heap size
  lineinfile:
    dest: /etc/elasticsearch/jvm.options
    regexp: '^-Xms2G$'
    line: '-Xms512m'

- name: Set elasticsearch maximum heap size
  lineinfile:
    dest: /etc/elasticsearch/jvm.options
    regexp: '^-Xmx2G$'
    line: '-Xmx512m'

- name: Starts and enable elasticsearch
  service:
    name: elasticsearch
    state: started
    enabled: yes
