// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package vpp

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonBa0ee0e3DecodeGithubComSkydiveProjectSkydiveTopologyProbesVpp(in *jlexer.Lexer, out *Metadata) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "SocketFilename":
			out.SocketFilename = string(in.String())
		case "ID":
			out.ID = int64(in.Int64())
		case "SocketID":
			out.SocketID = int64(in.Int64())
		case "Master":
			out.Master = bool(in.Bool())
		case "Mode":
			out.Mode = string(in.String())
		case "RingSize":
			out.RingSize = int64(in.Int64())
		case "BufferSize":
			out.BufferSize = int64(in.Int64())
		case "LinkUpDown":
			out.LinkUpDown = bool(in.Bool())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonBa0ee0e3EncodeGithubComSkydiveProjectSkydiveTopologyProbesVpp(out *jwriter.Writer, in Metadata) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"SocketFilename\":"
		out.RawString(prefix[1:])
		out.String(string(in.SocketFilename))
	}
	{
		const prefix string = ",\"ID\":"
		out.RawString(prefix)
		out.Int64(int64(in.ID))
	}
	{
		const prefix string = ",\"SocketID\":"
		out.RawString(prefix)
		out.Int64(int64(in.SocketID))
	}
	{
		const prefix string = ",\"Master\":"
		out.RawString(prefix)
		out.Bool(bool(in.Master))
	}
	{
		const prefix string = ",\"Mode\":"
		out.RawString(prefix)
		out.String(string(in.Mode))
	}
	{
		const prefix string = ",\"RingSize\":"
		out.RawString(prefix)
		out.Int64(int64(in.RingSize))
	}
	{
		const prefix string = ",\"BufferSize\":"
		out.RawString(prefix)
		out.Int64(int64(in.BufferSize))
	}
	{
		const prefix string = ",\"LinkUpDown\":"
		out.RawString(prefix)
		out.Bool(bool(in.LinkUpDown))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Metadata) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonBa0ee0e3EncodeGithubComSkydiveProjectSkydiveTopologyProbesVpp(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Metadata) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonBa0ee0e3EncodeGithubComSkydiveProjectSkydiveTopologyProbesVpp(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Metadata) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonBa0ee0e3DecodeGithubComSkydiveProjectSkydiveTopologyProbesVpp(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Metadata) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonBa0ee0e3DecodeGithubComSkydiveProjectSkydiveTopologyProbesVpp(l, v)
}
