// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  agent

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( Status ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* Status ) UnmarshalJSON([]byte) error { return nil }
func ( Status ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* Status ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_Status *Status
