---
- name: Make the container image available
  include_role:
    name: skydive_common
    tasks_from: container
  vars:
    skydive_docker_image: "{{ skydive_agent_docker_image }}"
    skydive_service_docker_image_tag: "{{ skydive_agent_docker_image_tag }}"

- name: Create systemd unit file
  include_role:
    name: skydive_common
    tasks_from: systemd
  vars:
    service_name: skydive-agent
    exec_start_pre: /usr/bin/{{ skydive_container_cli }} stop skydive-agent-{{ ansible_hostname }}
    exec_start: |
      /usr/bin/{{ skydive_container_cli }} run --rm \
        --privileged --net=host --pid=host \
        --user 0:0 \
        -v /var/run/libvirt:/var/run/libvirt \
        -v /var/run/openvswitch:/var/run/openvswitch \
        -v /var/run/runc-ctrs:/var/run/runc-ctrs:ro,shared \
        {% if skydive_container_cli == 'docker' %}
        -v /var/run/docker.sock:/var/run/docker.sock \
        {% endif %}
        -v /var/run/netns:/host/run:ro,shared \
        -v /etc/skydive/skydive.yml:/etc/skydive.yml \
        -e SKYDIVE_AGENT_TOPOLOGY_NETNS_RUN_PATH=/host/run {{ skydive_agent_docker_extra_env }} \
        -p {{ skydive_agent_port }}:{{ skydive_agent_port }} \
        --name=skydive-agent-{{ ansible_hostname }} \
        {{ skydive_docker_registry }}/{{ skydive_agent_docker_image }}:{{ skydive_agent_docker_image_tag or skydive_docker_image_tag }} \
        {{ skydive_agent_docker_command }}
    exec_stop_post: /usr/bin/{{ skydive_container_cli }} stop skydive-agent-{{ ansible_hostname }}
    user: root
    group: root
