# -*- mode: ruby -*-
# vi: set ft=ruby :

require 'vagrant-openstack-provider'

PREPARE_BOX=ENV.fetch("PREPARE_BOX", "") == "true" ? true : false
PROVISION_BOX=ENV.fetch("PROVISION_BOX", ENV.fetch("PREPARE_BOX", "")) == "true" ? true : false
SYNCED_FOLDER=ENV.has_key?("GOPATH") ? ENV.fetch("GOPATH") + "/src/github.com/skydive-project/skydive" : "../.."

$skydive_extra_config = {
  "http.ws.pong_timeout" => 10,
  "agent.topology.netlink.metrics_update" => 5,
  "analyzer.listen" => "0.0.0.0:8082",
  "analyzer.flow.backend" => "elasticsearch",
  "analyzer.topology.backend" => "elasticsearch",
  "storage.elasticsearch.host" => "127.0.0.1:9200"
}

$guest_additions_script = <<SCRIPT
sudo dnf -y install https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm
sudo dnf -y install kernel kernel-devel VirtualBox-guest-additions
latest=`rpm -q kernel-devel --qf '%{BUILDTIME} %{version}-%{release}.%{arch}\n' | sort -n -k 1 | tail -n 1 | awk '{print $2}'`
sudo akmods --kernels $latest
SCRIPT

$vagrant_insecure_key_script = <<SCRIPT
echo "ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEA6NF8iallvQVp22WDkTkyrtvp9eWW6A8YVr+kz4TjGYe7gHzIw+niNltGEFHzD8+v1I2YJ6oXevct1YeS0o9HZyN1Q9qgCgzUFtdOKLv6IedplqoPkcmF0aYet2PkEDo3MlTBckFXPITAMzF8dJSIFo9D8HfdOV0IAdx4O7PtixWKn5y2hMNG0zQPyUecp4pzC6kivAIhyfHilFR61RGL+GPXQ2MWZWFYbAGjyiYJnAmCP3NOTd0jMZEnDkbUvxhMmBYSdETk1rRgm+R4LOzFUGaHqHDLKLX+FIPKcF96hrucXzcWyLbIbEgE98OHlnVYCzRdK8jlqm8tehUc9c9WhQ== vagrant insecure public key" > ~/.ssh/authorized_keys
SCRIPT

$write_motd_script = <<SCRIPT
cat > /etc/motd <<'EOF'
                                  :##############;`
                             `'###';:::;';;;;;;'''+###`
                           ##+'';;:::::::::::;';;;''''+##
                        `##:,,,,,,,,,,:::'+################
                       ##:,,,,,,,,,,,,,+#+`:';::,,,,....:;+#
                     .#',,,,,,,,,,,,,+#,,';;::::,,,,..,;:` `
                   .##';;;;;;:::::::#+,:.,;;:::::;,
                  ##'::::,,,,,,,,,:#,'       ,            '
                .#',.,,,,,,,,,,,,++`'                     `
               ,#;.,,,,,,,,,,,,,#,`;                     :
              .#:.,,,,,,,,,,,,,#;`;                      ,
              #;,,,,,,,,,,,,,.'#`;                      .
             #',,,,,,,,,,,,,,,#``           `           ;
            #+';:::;;'''''''''#``           ,
           #'''';;:::,,::::::#``'           :          +
          #':,``.,:::::::::,'#`,            ;
         #':`,:::::::::::::.#```            +         #
        ++:.:::::::::::::::,#``             #
        #:`:::::::::::::::::#``             @        #
       +':::::::::::::::::.:#``             #
       #;:::::::::::::::::`:#``             '       '
       #::::::::::::::::::;'#```            ;       `
       #::::::::;''''''''';;#```            ,      ,
       #';''''';;;;;;;;;;;;'#``.            .      ,
       #';;,`,:;;;;;;;;;;;;:#``;            `     `
       #;`:;;;;;;;;;;;;;;;;,#``:                  ;
       #;:;;;;;;;;;;;;;;;;;.+;``
       #;;;;;;;;;;;;;;;;;;;:'#``,                +
       #':;;;;;;;;;;;;;;;;;;:#``'
       :+;;;;;;;;;;;;;;;;;;;`'#`;               #
        #+;;;;;;;;;;;;;:::,,,;#`.             ,:
         #+';;;;;;;;'''''++####.              '@@
          +############+':`      #         `  +@
            `                      `#         @
                `,'@+:`               `#   `,`
                          `,'@+:`         .@@@+
                                    `:'@@ #@@@@.
                                          #@@@@;
                                          .@@@#,
                                           ,#+,

# Welcome to the Skydive development image
#
# To go to the Skydive sources, use:
cd src/github.com/skydive-project/skydive
#
# To build Skydive, use:
make
# To run tests, use:
make test
make functional

EOF
SCRIPT

def populate_os_config(os, ip)
  os.openstack_auth_url = ENV.fetch("OS_AUTH_URL", "'http://keystone-server.net/v2.0/tokens'")
  os.username = ENV.fetch("OS_USERNAME", "openstackUser")
  os.password = ENV.fetch("OS_PASSWORD", "openstackPassword")
  os.tenant_name = ENV.fetch("OS_TENANT_NAME", "myTenant")
  os.flavor = ENV.fetch("OS_FLAVOR", "m1.large")
  os.image = ENV.fetch("OS_CENTOS_IMAGE", "centos")
  os.floating_ip_pool = ENV.fetch("OS_PUBLIC_IP_POOL", "8.0.0.0/8")
  os.networks = [
    'private',
    {
      name: 'vagrant',
      address: '192.168.10.10',
    },
  ]
end

Vagrant.configure(2) do |config|
  config.vm.define "dev" do |dev|
    dev.vm.hostname = "dev"
    dev.vm.synced_folder ".", "/vagrant", disabled: true
    dev.vm.synced_folder SYNCED_FOLDER, "/home/vagrant/src/github.com/skydive-project/skydive", disabled: false, :type => "nfs", :nfs_udp => false
    dev.vm.box = "skydive/skydive-dev"

    if PREPARE_BOX then
      # Install Python for ansible
      dev.vm.provision "common", type: "shell", inline: "sudo yum -y install python2 python-yaml libselinux-python"
      dev.vm.provision "shared-folders", type: "shell", inline: "sudo chown vagrant:vagrant /home/vagrant/src /home/vagrant/src/github.com /home/vagrant/src/github.com/skydive-project"
      dev.vm.provision "write-motd", type: "shell", inline: $write_motd_script
    end

    if PROVISION_BOX then
      dev.vm.provision :ansible_local do |ansible|
        ansible_extra_vars = {
          "skydive_extra_config" => $skydive_extra_config,
          "skydive_fabric_default_interface" => "eth0"
        }
        ansible.install = true
        ansible.provisioning_path = "/home/vagrant/src/github.com/skydive-project/skydive/contrib/ansible"
        ansible.playbook = "devmode.yml"
        ansible.extra_vars = ansible_extra_vars
        ansible.groups = {
          "dev" => "dev",
        }
        ansible.limit = "all"
        ansible.verbose = true
      end
    end

    dev.vm.provider :virtualbox do |vb, override|
      vb.gui = false
      vb.memory = "3072"
      override.vm.network "private_network", ip: "192.168.100.10"

      if PREPARE_BOX then
        override.vm.box = "fedora/27-cloud-base"
        override.vm.box_url = "https://download.fedoraproject.org/pub/fedora/linux/releases/27/CloudImages/x86_64/images/Fedora-Cloud-Base-Vagrant-27-1.6.x86_64.vagrant-virtualbox.box"

        override.vm.provision "guest-additions", type: "shell", inline: $guest_additions_script
        override.vm.provision :reload
      else
        override.vm.synced_folder SYNCED_FOLDER, "/home/vagrant/src/github.com/skydive-project/skydive", :type => "virtualbox"
      end
    end

    dev.vm.provider :libvirt do |domain, override|
      domain.memory = 3072
      domain.graphics_type = "none"
      override.vm.network "private_network", ip: "192.168.10.10"

      if PREPARE_BOX then
        override.vm.box = "f27-cloud-libvirt"
        override.vm.box_url = "https://download.fedoraproject.org/pub/fedora/linux/releases"\
                              "/27/CloudImages/x86_64/images/Fedora-Cloud-Base-Vagrant-27-1"\
                              ".6.x86_64.vagrant-libvirt.box"

        override.vm.provision "vagrant-insecure-key", type: "shell", privileged: false, inline: $vagrant_insecure_key_script
      end
    end

    dev.vm.provider :openstack do |os, override|
      populate_os_config(os, "192.168.10.10")
      os.security_groups = [ 'skydive' ]
    end

  end
end
