name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  sources:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
        cache-dependency-path: go.sum

  install-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Install pcap
        run: sudo apt-get install -y libpcap0.8-dev

  build:
    runs-on: ubuntu-latest
    needs:
      - sources
      - install-dependencies
    steps:
    - name: Build graffiti
      run: cd graffiti && go build -v

    - name: Build
      run: go build -v

  run:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Show version
        run: ./skydive version
